/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "timing.h"

u_long *
timing_1_svc(void *argp, struct svc_req *rqstp)
{
	static u_long  result;
	
	result = (unsigned long) time(NULL);

	return &result;
}
